export default 
[
   {
      "inputs":[
         {
            "internalType":"contract IRobot",
            "name":"robot",
            "type":"address"
         },
         {
            "internalType":"contract IERC20",
            "name":"tokenReward",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"AmountTokenReward",
            "type":"uint256"
         }
      ],
      "name":"OnBonusReward",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"startBlockLearn",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"pendingBlockLearn",
            "type":"uint256"
         }
      ],
      "name":"OnStartLearn",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"totalBlockLearnEachTime",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"stopBlockLearn",
            "type":"uint256"
         }
      ],
      "name":"OnStopLearn",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         }
      ],
      "name":"OnUpgradeLevelRobot",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"Paused",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"Unpaused",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"BlockUpgradeLevelRobotNFT",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"DataUserLearn",
      "outputs":[
         {
            "internalType":"bool",
            "name":"Learning",
            "type":"bool"
         },
         {
            "internalType":"uint256",
            "name":"StartBlockLearn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"StopBlockLearn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"PendingBlockLearn",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"DelayBlockLearnNextTime",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"ForRobotNFTStopLearn",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"ForRobotNFTToLearn",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"GameCotrollerContract",
      "outputs":[
         {
            "internalType":"contract IGameController",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"GetConfigSystem",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"maxLevelOfRobotNFTinGame",
            "type":"uint256"
         },
         {
            "internalType":"uint256[]",
            "name":"priceUpgradeLevelRobotNFTLevel",
            "type":"uint256[]"
         },
         {
            "internalType":"uint256",
            "name":"totalBlockLearnEachTime",
            "type":"uint256"
         },
         {
            "internalType":"uint256[]",
            "name":"rewardPerBlockOfLevel",
            "type":"uint256[]"
         },
         {
            "internalType":"uint256[]",
            "name":"blockUpgradeLevelRobotNFT",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         }
      ],
      "name":"GetData",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"cyberCreditBalance",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"levelRobotJoinGameOfUser",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"blockNumber",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"learning",
            "type":"bool"
         },
         {
            "internalType":"uint256",
            "name":"startBlockLearn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"stopBlockLearn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"pendingBlockLearn",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rewardPerDay",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"pendingBlockUpgradeLevelRobotNFT",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"MaxLevelOfRobotNFTInGame",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"PauseSystem",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"PendingBlockUpgradeLevelRobotNFT",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"PriceUpgradeLevelRobotNFT",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"RewardPerBlockOfLevel",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"Robot",
      "outputs":[
         {
            "internalType":"contract IRobot",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"quantityBlock",
            "type":"uint256"
         }
      ],
      "name":"SetBlockUpgradeLevelRobotNFT",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"newDelayBlockLearnNextTime",
            "type":"uint256"
         }
      ],
      "name":"SetDelayBlockLearnNextTime",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IGameController",
            "name":"gameCotrollerContract",
            "type":"address"
         }
      ],
      "name":"SetGameCotrollerContract",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"maxLevelOfRobotNFTinGame",
            "type":"uint256"
         }
      ],
      "name":"SetMaxLevelOfRobotNFTinGame",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"price",
            "type":"uint256"
         }
      ],
      "name":"SetPriceUpgradeLevelRobotNFT",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"level",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"value",
            "type":"uint256"
         }
      ],
      "name":"SetRewardPerBlockOfLevel",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IRobot",
            "name":"robot",
            "type":"address"
         }
      ],
      "name":"SetRobot",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IERC20",
            "name":"tokenReward",
            "type":"address"
         }
      ],
      "name":"SetTokenReward",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"totalBlockLearnEachTime",
            "type":"uint256"
         }
      ],
      "name":"SetTotalBlockLearnEachTime",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TokenReward",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TotalBlockLearnEachTime",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UnpauseSystem",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"UpgradeLevelRobot",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"bytes",
            "name":"",
            "type":"bytes"
         }
      ],
      "name":"onERC721Received",
      "outputs":[
         {
            "internalType":"bytes4",
            "name":"",
            "type":"bytes4"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"paused",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
]