export default
[
   {
      "inputs":[
         {
            "internalType":"contract IQuestionData",
            "name":"questionDataContract",
            "type":"address"
         },
         {
            "internalType":"contract IERC20",
            "name":"tokenReward",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"blockNumber",
            "type":"uint256"
         }
      ],
      "name":"OnDoQuestOnDay",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"totalAnswerCorrect",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"totalBonus",
            "type":"uint256"
         }
      ],
      "name":"OnResultQuestion",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"BlockReturnDoQuestion",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"BlockReturnSubmitQuestion",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"BonusAnswerCorrect",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"DelayToDoQuest",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"DoQuestOnDay",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"GameCotrollerContract",
      "outputs":[
         {
            "internalType":"contract IGameController",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         }
      ],
      "name":"GetDataQuest",
      "outputs":[
         {
            "components":[
               {
                  "internalType":"string",
                  "name":"Question",
                  "type":"string"
               },
               {
                  "internalType":"string",
                  "name":"Answer0",
                  "type":"string"
               },
               {
                  "internalType":"string",
                  "name":"Answer1",
                  "type":"string"
               },
               {
                  "internalType":"string",
                  "name":"Answer2",
                  "type":"string"
               },
               {
                  "internalType":"string",
                  "name":"Answer3",
                  "type":"string"
               }
            ],
            "internalType":"struct Quiz.Question[]",
            "name":"data",
            "type":"tuple[]"
         },
         {
            "internalType":"uint256",
            "name":"timeTheNextToDoQuest",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"timeTheNextSubmit",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"delayToDoQuest",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"blockReturnDoQuestion",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         }
      ],
      "name":"GetResultAnswers",
      "outputs":[
         {
            "internalType":"uint256[]",
            "name":"data",
            "type":"uint256[]"
         },
         {
            "internalType":"uint256",
            "name":"totalBonusToken",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"blockReturnSubmitQuestion",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"ListQuestionsUser",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"ListResultAnswersUser",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"QuestionDataContract",
      "outputs":[
         {
            "internalType":"contract IQuestionData",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"count",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"from",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"to",
            "type":"uint256"
         }
      ],
      "name":"RandomNumber",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"newBonusAnswerCorrect",
            "type":"uint256"
         }
      ],
      "name":"SetBonusAnswerCorrect",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"newDelayToDoQuest",
            "type":"uint256"
         }
      ],
      "name":"SetDelayToDoQuest",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IGameController",
            "name":"gameCotrollerContract",
            "type":"address"
         }
      ],
      "name":"SetGameCotrollerContract",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IQuestionData",
            "name":"newQuestionDataContract",
            "type":"address"
         }
      ],
      "name":"SetQuestionDataContract",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"contract IERC20",
            "name":"newTokenReward",
            "type":"address"
         }
      ],
      "name":"SetTokenReward",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"newTotalQuestionContract",
            "type":"uint256"
         }
      ],
      "name":"SetTotalQuestionContract",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"newTotalQuestionOnDay",
            "type":"uint256"
         }
      ],
      "name":"SetTotalQuestionOnDay",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256[]",
            "name":"results",
            "type":"uint256[]"
         }
      ],
      "name":"SubmitQuestions",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"TimeTheNextSubmit",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"TimeTheNextToDoQuest",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TokenReward",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TotalQuestionContract",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TotalQuestionOnDay",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
];